language: python

python:
    - "3.6.7"
services:
  - postgresql

install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codeclimate-test-reporter

before_script:
    - psql -c 'create database questioner;' -U postgres

script:
    - coverage run --source=app -m pytest && coverage report

branches:
    only:
      - develop

after_success:
    - coveralls
    - codeclimate-test-reporter
