language: python

python:
    - "3.6.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --source=app -m pytest && coverage report

branches:
    only:
      - develop

after_success:
    - coveralls
